import fs from 'node:fs';
const path='app/journey-page.tsx';let s=fs.readFileSync(path,'utf8');
s=s.replace('READ_START, clamp','READ_START, SCROLL_SCALE, clamp');
s=s.replace('unit*innerHeight','unit*innerHeight*SCROLL_SCALE');
s=s.replace('window.scrollY/viewportHeight','window.scrollY/(viewportHeight*SCROLL_SCALE)').replace('(JOURNEY_LENGTH+1)*viewportHeight','(JOURNEY_LENGTH*SCROLL_SCALE+1)*viewportHeight').replace('top:unit*viewportHeight','top:unit*viewportHeight*SCROLL_SCALE');
s=s.replace('let frame=0,last=', 'let frame=0,lastTarget=-1,lastPosition=-1,last=');
s=s.replace('const target=clamp(-section.getBoundingClientRect().top/viewportHeight,0,JOURNEY_LENGTH);','const target=clamp(window.scrollY/(viewportHeight*SCROLL_SCALE),0,JOURNEY_LENGTH);\n      if(document.hidden||(target===lastTarget&&Math.abs(position.current-target)<.0001)){frame=requestAnimationFrame(tick);return;}lastTarget=target;');
s=s.replace('-dt/75','-dt/45');
s=s.replace('innerWidth<700','false');
s=s.replace('CLOSE_START+1.4,CLOSE_START+2.1','CLOSE_START+3.4,CLOSE_START+4.1');
s=s.replace('`${(JOURNEY_LENGTH+1)*100}svh`','`${(JOURNEY_LENGTH*SCROLL_SCALE+1)*100}svh`');
s=s.replace('${CLOSE_START+1.4},${CLOSE_START+2.1}','${CLOSE_START+3.4},${CLOSE_START+4.1}');
s=s.replace('<section ref={journey}', '<div className="landscape-prompt" role="status"><span aria-hidden="true">↻</span><h2>A little world,<br/><em>best held sideways.</em></h2><p>Rotate your phone to landscape<br/>to enter the story.</p></div>\n    <section ref={journey}');
s=s.replace('lastPosition=-1,','');fs.writeFileSync(path,s);
const bp='app/journey-book.tsx';s=fs.readFileSync(bp,'utf8');
s=s.replace('READ_START, smooth','READ_START, TURN_START, smooth');
s=s.replace('renderer.shadowMap.type=THREE.PCFSoftShadowMap;','renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;');
s=s.replace('Math.min(devicePixelRatio,2)','Math.min(devicePixelRatio,1.5)');
s=s.replace('2048,2048','1024,1024');
s=s.replace('t.anisotropy=renderer.capabilities.getMaxAnisotropy()','t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy())');
s=s.replace('const t=loader.load(src);','const t=loader.load(src,()=>{dirty=true;});');
s=s.replace('const loader=new THREE.TextureLoader()', 'let dirty=true;\n    const loader=new THREE.TextureLoader()');
s=s.replace('setLoaded(true);','dirty=true;setLoaded(true);');
s=s.replace('const resize=()=>{renderer.setSize','const resize=()=>{dirty=true;renderer.setSize');
s=s.replace('const tick=()=>{','let previous=-1,rendered=0,frames=0;\n    const tick=()=>{');
s=s.replace('if(dead)return;const now=performance.now();','if(dead)return;frame=requestAnimationFrame(tick);const now=performance.now();');
s=s.replace('const p=position.current,mobile=parent.clientWidth<700,','const p=position.current,mobile=false,');
s=s.replace('finish=smooth(p,CLOSE_START+.9,CLOSE_START+1.95);','finish=smooth(p,CLOSE_START+.9,CLOSE_START+2.1);\n      const moving=Math.abs(p-previous)>.0001,settling=sheets.some(s=>!s.settled);\n      if(document.hidden||p<4.2||matchMedia("(max-width: 1024px) and (orientation: portrait) and (pointer: coarse)").matches)return;\n      if(!dirty&&!moving&&!settling)return;');
s=s.replace('smooth(raw-i,.78,1)','smooth(raw-i,TURN_START,1)');
s=s.replace('sheets.forEach((sheet,i)=>{','sheets.forEach((sheet,i)=>{\n        // Only the exposed spread and the turning leaf can contribute pixels.\n        sheet.pivot.visible=i>=index-1&&i<=index+1;');
s=s.replace('const forceFlat=flat&&','if(sheet.settled&&flat&&Math.abs(change)<.00001)return;\n        const forceFlat=flat&&');
s=s.replace('book.rotation.set((1-zoom)*.055+(!pause.current?Math.sin(time*.35)*.002*(1-zoom+finish):0),THREE.MathUtils.lerp(-.48,0,opening)+finish*(-.22+Math.sin(time*.3)*.12),.018*(1-opening));','const revolution=smooth(p,CLOSE_START+1.25,CLOSE_START+3.45);\n      book.rotation.set((1-zoom)*.065+finish*.035,THREE.MathUtils.lerp(-.48,.025,opening)+revolution*(Math.PI*3-.20),.018*(1-opening)-finish*.025);');
s=s.replace('book.scale.setScalar(THREE.MathUtils.lerp(scale,mobile?.59:.79,finish));','book.scale.setScalar(THREE.MathUtils.lerp(scale,.88,finish));');
s=s.replace('if(p>3.9)renderer.render(scene,camera);frame=requestAnimationFrame(tick);','renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);previous=p;dirty=false;frames++;\n      if(now-rendered>500){parent.dataset.drawCalls=String(renderer.info.render.calls);parent.dataset.renders=String(frames);parent.dataset.rotation=String(book.rotation.y);rendered=now;}');
fs.writeFileSync(bp,s);
